services:
  react-bun-type-kit:
    image: react-bun-type-kit
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - APP_ENV=${APP_ENV}
    env_file:
      - .env
    ports:
      - 3000:3000
    container_name: react-bun-type-kit_container
    volumes:
      - ./:/app
      - /app/node_modules